# Univariate Selection Methods

###### There are 2 methods  that fall under this category

### 1.SelectKBest

###### SelectKbest is used for findign the best features where k parameter determines the no. of best features we want.

In [1]:
import numpy as np
import pandas as pd

In [28]:
df = pd.read_csv('Iris.csv')
df


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [29]:
X.shape

(150, 5)

In [17]:
y = df['Species']
X = df.drop('Species',axis=1)

In [30]:
from sklearn.feature_selection import SelectKBest,chi2
model = SelectKBest(score_func=chi2,k=3)


In [31]:
z=model.fit_transform(X,y)

In [49]:
z.shape


(150, 3)

In [50]:
X.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'], dtype='object')

### Way of finding  Selected Features 

###### we use get_support function for finding the selected features

In [52]:
from array import array
filter = model.get_support()
features = X.columns
print("Selected Best 3:")
print(features[filter])
print(z)

Selected Best 3:
Index(['Id', 'PetalLengthCm', 'PetalWidthCm'], dtype='object')
[[1.00e+00 1.40e+00 2.00e-01]
 [2.00e+00 1.40e+00 2.00e-01]
 [3.00e+00 1.30e+00 2.00e-01]
 [4.00e+00 1.50e+00 2.00e-01]
 [5.00e+00 1.40e+00 2.00e-01]
 [6.00e+00 1.70e+00 4.00e-01]
 [7.00e+00 1.40e+00 3.00e-01]
 [8.00e+00 1.50e+00 2.00e-01]
 [9.00e+00 1.40e+00 2.00e-01]
 [1.00e+01 1.50e+00 1.00e-01]
 [1.10e+01 1.50e+00 2.00e-01]
 [1.20e+01 1.60e+00 2.00e-01]
 [1.30e+01 1.40e+00 1.00e-01]
 [1.40e+01 1.10e+00 1.00e-01]
 [1.50e+01 1.20e+00 2.00e-01]
 [1.60e+01 1.50e+00 4.00e-01]
 [1.70e+01 1.30e+00 4.00e-01]
 [1.80e+01 1.40e+00 3.00e-01]
 [1.90e+01 1.70e+00 3.00e-01]
 [2.00e+01 1.50e+00 3.00e-01]
 [2.10e+01 1.70e+00 2.00e-01]
 [2.20e+01 1.50e+00 4.00e-01]
 [2.30e+01 1.00e+00 2.00e-01]
 [2.40e+01 1.70e+00 5.00e-01]
 [2.50e+01 1.90e+00 2.00e-01]
 [2.60e+01 1.60e+00 2.00e-01]
 [2.70e+01 1.60e+00 4.00e-01]
 [2.80e+01 1.50e+00 2.00e-01]
 [2.90e+01 1.40e+00 2.00e-01]
 [3.00e+01 1.60e+00 2.00e-01]
 [3.10e+01 1.60e+00 

### 2.SelectPercentile

###### Selecting featues according to percentile of the highest score

In [57]:
from sklearn.datasets import load_digits
from sklearn.feature_selection import SelectPercentile,chi2
X, y = load_digits(return_X_y=True)
X.shape


(1797, 64)

In [67]:
MODEL = SelectPercentile(chi2,percentile=20)
z=MODEL.fit_transform(X,y).shape



###### For regression tasks: f_regression, mutual_info_regression
For classification tasks: chi2, f_classif, mutual_info_classif

